version: '3'
services:
  answer:
    container_name: answer
    build: ./answer
    hostname: answer
    restart: always
    ports:
      - "6060:6060"
  offer:
    container_name: offer
    build: ./offer
    hostname: offer
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - "answer"